name: Generate Markdown Hints

on: [push]

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: make deps gen
      - uses: actions/upload-artifact@v3
        with:
          name: hints.md
          path: out/hints.md
